version: '3.8'

services:
  app:
    container_name: go_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=taskmanagement
      - DB_PORT=5432

  db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskmanagement
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
